### ISSUE TITLE
Removed from CRAN

### ISSUE THREAD

**Issue by muschellij2** [R-ArcGIS/arcgis#11]
Is this going back on CRAN?  Removed in August: https://cran.r-project.org/package=arcgis

**Comment by muschellij2** [comment]
What do you mean "review one of the dependencies"? Usually things stay up unless errors/warnings and usually fixes are automatically included if passing.  I will install from r-universe to get this to work for our students and researchers.

**Comment by JosiahParry** [comment]
Package submissions are manually reviewed by a group of volunteers on CRAN before publication.
